# NOTE: Do NOT use this config in your own repositories. Instead, see 
#   docs/integrations.md
repos:
- repo: local
  hooks:
  - id: julia-formatter
    name: "Julia Formatter"
    entry: "${HOME}/.julia/bin/jlfmt --inplace"
    pass_filenames: true
    always_run: false
    types: [file]
    files: \.(jl|[jq]?md)$
    exclude: '^test/'
    language: "system"
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes