name = "JuliaFormatter"
uuid = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
authors = ["Dominique Luna <dluna132@gmail.com>"]
version = "0.1.6"

[deps]
CSTParser = "00ebfdb7-1f24-5e51-bd34-a7502290713f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Tokenize = "0796e94c-ce3b-5d07-9a54-7f471281c624"

[compat]
julia = "1"
CSTParser = "0.6.2"
Tokenize = "0.5.5"
