name = "JuliaFormatter"
uuid = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
authors = ["Dominique Luna <dluna132@gmail.com>"]
version = "2.0.0"

[deps]
CommonMark = "a80b9123-70ca-4bc0-993e-6e3bcb318db6"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
CommonMark = "0.5, 0.6, 0.7, 0.8"
Glob = "1.3"
JuliaSyntax = "0.4.10"
Pkg = "1"
PrecompileTools = "1"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
